### ISSUE TITLE
Expose current Faction of NSO

### ISSUE THREAD

**Issue by leonhard-s** [cooltrain7/Planetside-2-API-Tracker#4]
There is currently no way to tell what faction an NSO is on through the API. This makes differentiating teamkills from regular kills impossible with NSO players when processing the `Death` events sent through the Streaming API.

A solution would be exposing a `current_faction_id` key in the payloads sent for for `Death` events that can be used to see if an NSO killer was on the same faction as their victim. For any other factions, this field would be equal to their regular faction.

**Comment by Maelstromeous** [comment]
Imo this an **absolute must** prior to NSO overhaul.

**Comment by cooltrain7** [comment]
Compressing into a megathread issue.
