### ISSUE TITLE
ContinentUnlock responses missing

### ISSUE THREAD

**Issue by leonhard-s** [cooltrain7/Planetside-2-API-Tracker#5]
`ContinentUnlock` events don't get sent when a continent unlocks and have been missing for years.
The corresponding `ContinentLock` events are fine and healthy though.

**Comment by cooltrain7** [comment]
### [DBG]MangoBean - Planetside discord, [api-dev channel](https://discord.com/channels/251073753759481856/451032574538547201/1050511427804348446): 
_More of a feature request as they were never implemented. I've got a ticket in the backlog for it._

**Comment by leonhard-s** [comment]
Closing as 'wontfix'. The documentation has been updated accordingly.

Source:
> ***MangoBean***, *PlanetSide 2 Community Developer Discord, [#census-general>✉](https://discord.com/channels/1019343142471880775/1019509468754608168/1101292366809268294)*
>
> ContinentUnlock has been removed from documentation, unless I missed a spot. It was never implemented.
