### ISSUE TITLE
NSO loadout entries missing

### ISSUE THREAD

**Issue by leonhard-s** [cooltrain7/Planetside-2-API-Tracker#6]
The NSO classes are missing from the `ps2/loadout` collection.

I did some testing comparing kill loadout IDs with weapons fire modes and profiles; this is the data that's missing:

| `loadout_id` | `profile_id` | `faction_id` | `code_name`       |
|--------------|--------------|--------------|-------------------|
| 28           | 190          | 4            | NSO Infiltrator   |
| 29           | 191          | 4            | NSO Light Assault |
| 30           | 192          | 4            | NSO Medic         |
| 31           | 193          | 4            | NSO Engineer      |
| 32           | 194          | 4            | NSO Heavy Assault |
| 45           | 252          | 4            | NSO MAX           |

**Comment by cooltrain7** [comment]
Compressing into a megathread issue.
