### ISSUE TITLE
Need final review of new Weapons directory layout and readme files

### ISSUE THREAD

**Issue by fredkilbourn** [cooltrain7/Planetside-2-API-Tracker#78]
@cooltrain7 Now that the last unsanctioned weapons are finally merged into the community list, I've reorganized the directory structure a little and updated the readme files.

Can you please:
* Let me know if the structure and readmes look ok?
* Let me know if the sanction list file names are a good format to you or if we should change/organize at all?

**Comment by cooltrain7** [comment]
That looks really good! I can't spot anything I think I would change. I'll have to look into the workflows/actions in the future to see if we can get an auto-build when we have changes to those files.

**Comment by cooltrain7** [comment]
That looks really good! Great job putting it all together. I'll have to look into the workflows/actions in the future to see if we can get an auto-build when we have changes to those files.
