### ISSUE TITLE
MetagameEvent payloads missing zone_id field

### ISSUE THREAD

**Issue by leonhard-s** [cooltrain7/Planetside-2-API-Tracker#8]
The `MetagameEvent` streaming event payloads are missing the `zone_id` field mentioned in the documentation.

The ID fields in the `ps2/metagame_event` collection are however mostly zone-specific, it is therefore possible to map them to their respective zones client-side.

Here is my table of `metagame_event_id`s and their associated `zone_id`s: https://github.com/leonhard-s/auraxium/wiki/Alert-ID-Reference

**Comment by cooltrain7** [comment]
`zone_id` is now part of Metagame world events. 

Using the Outfit Wars `zone_id` you can also calculate the `instance_id` and `definition_id`

> Sorry the world isn’t contained in the zone_id mask, but the zone_id is only unique for each world.  E.g. there might be 2 of the same exact values from 2 different worlds.
> 
> There are a number of good resources online for BitMasks, effectively the zone_id for dynamic zones is a combo, the top 16 bits are the instance # and the bottom 16 bits are the definition ids
> 
> Desolation definition id iirc is 299 or something so the first desolation zone created zone_id will be in hex: 0x0001012B
> 
> If you mask and shift ((zone_id)(0xFFFF0000)>>16) you get the instance id and if you just mask ((zone_id)0x0000FFFF) you get the definition id: 299
