### ISSUE TITLE
Document item_ids from the _Integration update and add to sanction list

### ISSUE THREAD

**Issue by fredkilbourn** [cooltrain7/Planetside-2-API-Tracker#80]
Here's what I've seen so far, looking for input for anyone who's figured any of them out, please comment below if you know and I'll try and update this comment as I get feedback:

```csv
Item ID,Item Category,Item Name
6009860,??DERVISH/0??,DV-22 Raycaster
6009861,??DERVISH/0??,DV-22T Lightweaver
6009927,??DERVISH/0??,DV-XE
6009928,??DERVISH/0??,DV-21 Lotus
6009991,??DERVISH/0??,DV-LAT Pixie
6009992,??DERVISH/0??,DV-XAT
```

**Comment by fredkilbourn** [comment]
Got most of what we needed from Rhett on #api-dev, all we need now are item category names for the new vehicles.

**Comment by fredkilbourn** [comment]
All we need now is the Dervish weapon categories

**Comment by cooltrain7** [comment]
Is this request still active or has it become outdated?

**Comment by fredkilbourn** [comment]
Still don't have the official weapon category names for this, I'll see if I can figure them out again.

See all the `UNKNOWN` prefixed categories for weapons starting `DV-` here:
https://github.com/cooltrain7/Planetside-2-API-Tracker/blob/master/Weapons/sanction-list.csv#L1451

**Comment by cooltrain7** [comment]
I've recently started looking at the internal data (So we can look this kind of stuff up for ourself when we need it):

- Dervish weapons don't have a CategoryID set internally for them.
- But there is a string in the string table called `Dervish Top Turret` that looks like a category name.
- Dervish Top Turret string hash is `2664312037` so a very dirty reverse the string id used for lookup is `6014921`
- That id isn't currently used by any of the files inside `data_x64_0`

Hope any of that helps either directly or indirectly

**Comment by fredkilbourn** [comment]
I suppose I'll just base it off the in-game labels until it (ever) shows up in the API:

![image](https://user-images.githubusercontent.com/658757/143952542-485b7d1b-98be-4c22-8762-0cdfc1b0b9f4.png)

`Nose Cannon` and `Dervish Top Turret`

**Comment by fredkilbourn** [comment]
Or should we say `Dervish Nose Cannon`?

**Comment by cooltrain7** [comment]
> Or should we say `Dervish Nose Cannon`?

I would got with that yes ^^
