### ISSUE TITLE
Bushwhacker title

### ISSUE THREAD

**Issue by elmagow** [cooltrain7/Planetside-2-API-Tracker#93]
Little update for the titles.csv:

You can get the Bushwhacker title, by destroying plants in the new containment sites on Esamir near B point, about 100 iirc. 
Then interact with the big plant at the B point entry, and it will give you the title after some dialogues

Good luck for fitting that into the table D:

**Comment by cooltrain7** [comment]
Wanted to check it myself - TY again for the report. Updated.
