### ISSUE TITLE
Possible typo single_character_by_id on friends resolve

### ISSUE THREAD

**Issue by microwavekonijn** [cooltrain7/Planetside-2-API-Tracker#95]
The collection `single_character_by_id` can resolve `friends`, however the `friends_list` property that is added will always return an empty array. This is probably due to that `friends_list` is whitelisted but the joined collection(`characters_friend`) uses `friend_list`.

**Comment by cooltrain7** [comment]
It also works if you resolve `friends` with `character`, so I think you might be right.

**Comment by microwavekonijn** [comment]
It is fixed, what crazy world have we entered :D
